name: Prueba Github Actions Universidad Siglo XXI
run-name: Antonio esta probando Github Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Instalar Python en ambiente de pruebas
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run unittests
      run: |
        python -m unittest discover -s . -p "test_*.py"